### ISSUE TITLE
Problem with elasticsearch 2.4

### ISSUE THREAD

**Issue by StefanSa** [gigya/kibana#11]
Hi there, thanks for this Kibana fork.
i have here ES 2.4, but i get no data displayed only this error in the ES log file 

`[192.168.1.67:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1473427523559] with format [dateOptionalTime]]; nested: IllegalArgumentException[Invalid format: "1473427523559" is malformed at "3559"];
Caused by: ElasticsearchParseException[failed to parse date field [1473427523559] with format [dateOptionalTime]]; nested: IllegalArgumentException[Invalid format: "1473427523559" is malformed at "3559"];
`
any help here.
thx
Stefan

**Comment by lee-elenbaas** [comment]
@ehudl Any chance you can give me some more info on this?

**Comment by StefanSa** [comment]
Lee, have you testet this fork on ES 2.4 ?
This error i get when opening the logstash standard desktop.

Example Event over Time rquest, here ist the @timestamp field from / to wrong
` Logstash Search
a day ago to a few seconds ago 
QUERY 

*

FILTERING 

EVENTS OVER TIME
View  |   Zoom Out |  count per 10m | ( hits)

ALL EVENTS
Fields 
All (296) / Current (0)

Type to filter...
0 to 0 of available for paging
_source (select columns from the list to the left)
0 to 0 of available for paging
 ADD A ROW
×
Last Elasticsearch Query
curl -XGET 'http://192.168.1.67:9200/logstash-2016.09.11,logstash-2016.09.10/_search?pretty' -d '{
  "size": 0,
  "aggs": {
    "0": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "from": 1473528561582,
                  "to": 1473614961582
                }
              }
            },
            {
              "fquery": {
                "query": {
                  "query_string": {
                    "query": "*"
                  }
                }
              }
            }
          ]
        }
      },
      "aggs": {
        "dh": {
          "date_histogram": {
            "field": "@timestamp",
            "interval": "10m"
          }
        }
      }
    }
  }
}'

Close
`
Perhaps the datefield has changed in ES 2.4.

**Comment by lee-elenbaas** [comment]
@StefanSa, i have not tested it on ES 2.4 - and not sure i will have time to do it in the coming week
i talked to @ehudl and he does not seem to be having the time to handle it right now
but we will try to give it some time afterwards

can you show your field declaration for @timestamp?

**Comment by ldumont** [comment]
Hi,

We are currently testing the current master against Elasticsearch 2.4.1 and we have no such issue with our dashboards (as well as the log stash dashboard).

The only issue is with histogramTransformer but I don't think it's related to ES 2.4.x. I will provide a PR for this one.

Regards,

**Comment by lee-elenbaas** [comment]
@ldumont thanks - i have not been able to run a test with ES 2.4 so far
@StefanSa can you check if you still get the same issue?

**Comment by faxm0dem** [comment]
I just stumbled upon this.
There is an easy workaround which unfortunately requires reindexing: you need to add `epoch_millis` to your index mapping template.

A proper fix would be to change the date ranges to force the format to `epoch_millis` as [stated in the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-range-query.html#_date_format_in_range_queries)
