### ISSUE TITLE
Add support for ordering in term panels

### ISSUE THREAD

**Issue by ldumont** [gigya/kibana#14]
I noticed that the order field (count, term, ...) in term panel was not working and by looking at the source code it looks like it's not implemented. 

Here is a proposal, let me know if it's the correct place to do it and if the code could be better: https://github.com/ldumont/kibana/commit/61873c406366382295af6f2e3b1602efa6558adc

Then I will submit a PR.

**Comment by lee-elenbaas** [comment]
makes sense to me - just make room also for not ordering at all

**Comment by ldumont** [comment]
Finally back on this...

I think that Kibana will always provide an ordering ('count' is the default ordering when you add a term panel), but should I add a case anyway? And which case?

**Comment by lee-elenbaas** [comment]
leave it out then
