### ISSUE TITLE
topN queries

### ISSUE THREAD

**Issue by abiruth84** [gigya/kibana#2]
Hi, 
in our old kibana3 we were using in our dashboard TopN query provided. But after migrating it seems is not working properly anymore. 
Kibana was installed from here: https://github.com/gigya/kibana/tree/master
ES version is 2.1.1

We apply the query in a table panel and some fields are totally messed somehow. 
Could be an issue because TopN was based on facets? Has anyone experience issues with it? 
thanks and kind regards

**Comment by lee-elenbaas** [comment]
i'll take a look and see how it can be fixed - but i will not get to it in the coming week

**Comment by wleese** [comment]
@abiruth84 here's a go at that functionality, that and the trends panel.
We're moving to this fork (or a fork of this work) so I'm interested in having all functionality working properly. Let me know if you run into anything.

PR: https://github.com/gigya/kibana/pull/6
In our own fork: https://github.com/bolcom/kibana/tree/wleese_3.0_topn_trends

**Comment by wleese** [comment]
Just added a fix for topn + hits panel
