### ISSUE TITLE
Add elasticsearch 2.3 support

### ISSUE THREAD

**Issue by bloublou2014** [gigya/kibana#3]
Hello,

I updated my fork (https://github.com/bloublou2014/kibana) with your last updates, corrected some JSLint/JsHint problems, package.json, and built via grunt.

With elasticsearch 2.3.2 a couple of updates have to be done  : 
- add plugin-descriptor.properties file
- add compiled kibana on _site directory
- add install instruction on readme.md

if you are interested i can make a pull request.

**Comment by lee-elenbaas** [comment]
PR will be great

**Comment by bloublou2014** [comment]
PR Added, i close this issue
